{{- if .Values.global.gateway_ssl.alertmanager.create -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.global.gateway_ssl.alertmanager.name }}
  namespace: {{ .Values.alertmanager.namespace }}
spec:
  hosts:
    {{- range .Values.global.gateway_ssl.alertmanager.hosts }}
      - {{ . | quote }}
    {{- end }}
  gateways:
  - {{ .Values.global.gateway_ssl.alertmanager.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.alertmanager.name }}
        port:
          number: 9093
{{- end }}
