{{- if .Values.global.gateway_ssl.alertmanager.create -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.global.gateway_ssl.alertmanager.name }}
  namespace: {{ .Values.alertmanager.namespace }}
spec:
  selector:
    gateway: {{ .Values.global.gateway_ssl.alertmanager.via }}
  servers:
    - hosts:
     {{- range .Values.global.gateway_ssl.alertmanager.hosts }}
       - {{ . | quote }}
     {{- end }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: {{ .Values.global.gateway_ssl.alertmanager.credentialName }}
        {{ if .Values.global.gateway_ssl.chainCertificate }}
        mode: MUTUAL
        {{ else }}
        mode: SIMPLE
        {{ end }}
{{- end }}
